name: Lint & Test
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt
          mkdir dist
      - name: Run pytest
        run: pytest
      - name: Run black
        run: black --check duke tests
      - name: Run isort
        run: isort --check-only .
      - name: Run mypy
        run: mypy duke
      - name: Run flake8
        run: flake8 duke
      - name: Run pydocstyle
        run: pydocstyle duke**/*
